// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:5158d30f-71ee-458e-874e-d24ac49b7b8a",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_QA2Yn8qWd",
    "aws_user_pools_web_client_id": "73mnh3goljn0laan4duh1lun4h",
    "oauth": {},
    "aws_content_delivery_bucket": "singularity-product",
};


export default awsmobile;
